import { readFile, writeFile } from "fs/promises";
import { join } from "path";
import yaml from "js-yaml";

const PROJECTS_PATH = join(process.cwd(), "data", "projects.yaml");
const PROJECT_PAGES_PATH = join(process.cwd(), "data", "projectPages.yaml");
const PROJECT_SITE_BUILDS_PATH = join(process.cwd(), "data", "projectSiteBuilds.yaml");
const GITHUB_TOKEN = process.env.GITHUB_TOKEN || "";
const GITHUB_OWNER = process.env.GITHUB_OWNER || "agis-eng";

async function loadYaml<T>(path: string, fallback: T): Promise<T> {
  try {
    const raw = await readFile(path, "utf8");
    return (yaml.load(raw, { schema: yaml.JSON_SCHEMA }) as T) || fallback;
  } catch {
    return fallback;
  }
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

function safeComponentName(value: string) {
  const cleaned = String(value || "Website").replace(/[^a-zA-Z0-9]+/g, " ").trim();
  return (cleaned || "Website")
    .split(/\s+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
    .replace(/^[0-9]/, "Site");
}

function buildSiteFiles(project: any, page: any) {
  const componentName = `${safeComponentName(project.name)}Page`;
  const code = String(page.pageCodeDraft || "").replace(/export default function\s+[A-Za-z0-9_]+\s*\(/, `export default function ${componentName}(`);
  const title = page?.seoLayer?.suggestedTitle || page?.headline || project.name;
  const description = page?.seoLayer?.suggestedMeta || project.summary || page?.subheadline || project.name;

  return {
    "package.json": JSON.stringify({
      name: slugify(project.name || "website"),
      private: true,
      version: "0.1.0",
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "16.2.1",
        react: "19.1.1",
        "react-dom": "19.1.1",
      },
    }, null, 2),
    "tsconfig.json": JSON.stringify({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: false,
        skipLibCheck: true,
        strict: false,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    }, null, 2),
    "next.config.ts": "import type { NextConfig } from 'next';\nconst nextConfig: NextConfig = {};\nexport default nextConfig;\n",
    "next-env.d.ts": "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// This file is auto-generated by Next.js\n",
    "app/layout.tsx": `import './globals.css';\nimport type { Metadata } from 'next';\n\nexport const metadata: Metadata = {\n  title: ${JSON.stringify(title)},\n  description: ${JSON.stringify(description)},\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n`,
    "app/globals.css": `:root {\n  color-scheme: dark;\n  --background: #09090b;\n  --foreground: #fafafa;\n  --muted: #18181b;\n  --muted-foreground: #a1a1aa;\n  --card: #111113;\n  --border: #27272a;\n}\n* { box-sizing: border-box; }\nhtml, body { margin: 0; padding: 0; background: var(--background); color: var(--foreground); font-family: Inter, ui-sans-serif, system-ui, sans-serif; }\na { color: inherit; text-decoration: none; }\nbutton { font: inherit; cursor: pointer; }\n.bg-background { background: var(--background); }\n.text-foreground { color: var(--foreground); }\n.text-background { color: var(--background); }\n.text-muted-foreground { color: var(--muted-foreground); }\n.bg-card { background: var(--card); }\n.bg-muted { background: var(--muted); }\n.border-border { border-color: var(--border); }\n.min-h-screen { min-height: 100vh; }\n.mx-auto { margin-left: auto; margin-right: auto; }\n.max-w-6xl { max-width: 72rem; }\n.max-w-3xl { max-width: 48rem; }\n.max-w-2xl { max-width: 42rem; }\n.px-6 { padding-left: 1.5rem; padding-right: 1.5rem; }\n.py-24 { padding-top: 6rem; padding-bottom: 6rem; }\n.py-16 { padding-top: 4rem; padding-bottom: 4rem; }\n.py-32 { padding-top: 8rem; padding-bottom: 8rem; }\n.pb-12 { padding-bottom: 3rem; }\n.p-5 { padding: 1.25rem; }\n.p-6 { padding: 1.5rem; }\n.p-8 { padding: 2rem; }\n.p-12 { padding: 3rem; }\n.rounded-full { border-radius: 9999px; }\n.rounded-2xl { border-radius: 1rem; }\n.rounded-3xl { border-radius: 1.5rem; }\n.border { border-width: 1px; border-style: solid; }\n.text-sm { font-size: 0.875rem; }\n.text-lg { font-size: 1.125rem; }\n.text-3xl { font-size: 1.875rem; line-height: 1.2; }\n.text-4xl { font-size: 2.5rem; line-height: 1.1; }\n.text-6xl { font-size: 4rem; line-height: 1; }\n.font-semibold { font-weight: 600; }\n.font-medium { font-weight: 500; }\n.tracking-tight { letter-spacing: -0.02em; }\n.uppercase { text-transform: uppercase; }\n.flex { display: flex; }\n.grid { display: grid; }\n.flex-wrap { flex-wrap: wrap; }\n.items-center { align-items: center; }\n.gap-3 { gap: 0.75rem; }\n.gap-4 { gap: 1rem; }\n.gap-6 { gap: 1.5rem; }\n.space-y-4 > * + * { margin-top: 1rem; }\n.space-y-6 > * + * { margin-top: 1.5rem; }\n@media (min-width: 768px) {\n  .md\\:py-24 { padding-top: 6rem; padding-bottom: 6rem; }\n  .md\\:py-32 { padding-top: 8rem; padding-bottom: 8rem; }\n  .md\\:text-6xl { font-size: 4rem; line-height: 1; }\n  .md\\:grid-cols-3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }\n  .md\\:p-12 { padding: 3rem; }\n}\n`,
    "app/page.tsx": code,
    "README.md": `# ${project.name}\n\nGenerated by Atlas Dashboard from project website builder.\n\n## Source draft\n- Draft: ${page.id}\n- Project: ${project.id}\n\n## Run locally\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
  } as Record<string, string>;
}

async function githubRequest(path: string, init: RequestInit = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "User-Agent": "Atlas-Dashboard",
      ...(init.headers || {}),
    },
  });
  const text = await res.text();
  let data: any = null;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    data = text;
  }
  if (!res.ok) {
    throw new Error((data && (data.message || data.error)) || `GitHub API error (${res.status})`);
  }
  return data;
}

async function createRepoAndCommitFiles(repoName: string, files: Record<string, string>) {
  const repo = await githubRequest(`/orgs/${GITHUB_OWNER}/repos`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name: repoName,
      private: true,
      auto_init: false,
      description: `Website generated by Atlas Dashboard for ${repoName}`,
    }),
  });

  for (const [path, content] of Object.entries(files)) {
    await githubRequest(`/repos/${GITHUB_OWNER}/${repoName}/contents/${encodeURIComponent(path).replace(/%2F/g, "/")}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message: `Initial site build: ${path}`,
        content: Buffer.from(content).toString("base64"),
        branch: "main",
      }),
    });
  }

  return {
    repoUrl: repo.html_url,
    branch: "main",
  };
}

export async function buildWebsiteRepoForProject(projectId: string) {
  const [projectsData, pagesData, buildsData] = await Promise.all([
    loadYaml<{ projects: any[] }>(PROJECTS_PATH, { projects: [] }),
    loadYaml<{ projectPages: any[] }>(PROJECT_PAGES_PATH, { projectPages: [] }),
    loadYaml<{ builds: any[] }>(PROJECT_SITE_BUILDS_PATH, { builds: [] }),
  ]);

  const project = (projectsData.projects || []).find((item) => item.id === projectId);
  if (!project) {
    throw new Error("Project not found");
  }
  if (project.liveUrl || project.previewUrl || project.repoUrl) {
    throw new Error("Project already has a site or repo; use redesign flow instead.");
  }
  if (!GITHUB_TOKEN) {
    throw new Error("GitHub token not configured for site build");
  }

  const latestPage = (pagesData.projectPages || []).find((item) => item.projectId === projectId);
  if (!latestPage) {
    throw new Error("Create a website draft first");
  }
  if (!latestPage.pageCodeDraft) {
    throw new Error("Latest draft does not contain site code");
  }

  const repoName = slugify(project.name || projectId);
  const files = buildSiteFiles(project, latestPage);
  const github = await createRepoAndCommitFiles(repoName, files);

  const buildRecord = {
    id: `site-build-${projectId}-${Date.now()}`,
    projectId,
    pageId: latestPage.id,
    repoName,
    repoUrl: github.repoUrl,
    branch: github.branch,
    status: "repo-created",
    framework: "nextjs",
    createdAt: new Date().toISOString(),
    files: Object.keys(files),
    title: latestPage.name || project.name,
  };

  buildsData.builds = [buildRecord, ...(buildsData.builds || [])];
  await writeFile(PROJECT_SITE_BUILDS_PATH, yaml.dump(buildsData, { lineWidth: -1, noRefs: true, quotingType: '"', forceQuotes: false }), "utf8");

  project.repoUrl = github.repoUrl;
  project.githubBranch = github.branch;
  project.lastUpdate = new Date().toISOString().split("T")[0];
  if (!project.brain) project.brain = {};
  if (!project.brain.notes) project.brain.notes = [];
  project.brain.notes.unshift(`Website repo created from draft ${latestPage.id}: ${github.repoUrl}`);
  await writeFile(PROJECTS_PATH, yaml.dump(projectsData, { lineWidth: -1, noRefs: true, quotingType: '"', forceQuotes: false }), "utf8");

  return {
    buildRecord,
    project,
  };
}
